---
title: "Project 1 - Data processing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE,
                      message = FALSE, 
                      cache = FALSE)
```

```{r}
library(ggplot2)
library(dplyr)

data1 <- read.csv(file="listings_2.csv", header=TRUE, sep=",")
data2 <- read.csv(file="listings.csv", header=TRUE, sep=",")

```

```{r}
columns1 <- colnames(data1)
columns2 <- colnames(data2)

## Removing url columns
temp <- data1[, -grep("_url", colnames(data1))]

## Remove columns with descriptions
temp <- temp[, -which(names(temp) %in% c("summary","description","experiences_offered","notes",
                                            "neighborhood_overview","transit","access","interaction",
                                            "house_rules","host_about","space"))]

## Remove host related information

temp <- temp[, -which(names(temp) %in% c("host_location","host_response_time","host_response_rate",
                                         "host_acceptance_rate","host_is_superhost","host_neighbourhood",
                                         "host_verifications","host_total_listings_count","host_since",
                                         "host_listings_count","host_has_profile_pic","host_identity_verified"))]

## Remove scaping related information
temp <- temp[,  -grep("scrape", colnames(temp))]

## Remove location related information

temp <- temp[, -which(names(temp) %in% c("street","city","state","smart_location",
                                         "neighbourhood","country","country_code",
                                         "is_location_exact","market"))]

## Remove room related information

temp <- temp[, -which(names(temp) %in% c("property_type","bathrooms","bedrooms","bed_type",
                                         "beds","square_feet"))]

## Remove price related information

temp <- temp[, -which(names(temp) %in% c("weekly_price","monthly_price","security_deposit",
                                         "cleaning_fee","guests_included","extra_people"))]

## Remove misc information

temp <- temp[, -which(names(temp) %in% c("calendar_updated","has_availability","availability_30",
                                         "availability_60","availability_90","requires_license","license",
                                         "jurisdiction_names","is_business_travel_ready",
                                         "cancellation_policy","require_guest_profile_picture",
                                         "require_guest_phone_verification","instant_bookable"))]

write.csv(temp, file = "cleaned_data.csv")

```