---
title: "Interactive_Component"
output: html_document
---

## 6.Interactive Component

From the data analysis we were able to observe the room type distribution of the boroughs, price distributions of boroughs and other plots distributed by borough. To observe things at a more granular geographic level, we wanted to look into neighbourhood level plots and to do that, we worked on NYC map with click actions that provided information about the neighbourhood. The link for the interative component is: <https://bl.ocks.org/gmidhun3845/raw/bcfa9e0b40741fa15e815f5e2ca94be3/2db3757fdd2ef89c9954c490ffbeb932d8f0519e/>

We attempted to provide the types of rooms available in each neighbourhood of New York City. When a user clicks on the neighbourhood of interest, information about the neighbourhood is populated in the bar chart. The interactive component can be further developed to provide users with relavant information from each neighbourhood and process queries from the users to highlight suitable neighbourhoods for the users.